# ----------------------------------------------------------------------------
#
# Package             : abyss
# Source Repo         : https://github.com/bcgsc/abyss
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/abyss/builds/213756668
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: cpp
arch:
  - amd64
  - ppc64le
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libgtest-dev libopenmpi-dev libsparsehash-dev
  - |
    if [[ "$TRAVIS_CPU_ARCH" = "ppc64le" ]]; then
     sudo apt-get install g++-4.8  # To fix the compilation error
     sudo rm -rf /usr/bin/g++
     sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
    fi
script:
  - ./autogen.sh
  - ./configure --with-mpi=/usr/lib/openmpi
  - make
  - make check
