# ----------------------------------------------------------------------------
#
# Package             : apiguardian-api
# Source Repo         : https://github.com/apiguardian-team/apiguardian.git
# Travis Job Link     : https://travis-ci.com/github/rajesh-ibm-power/apiguardian
# Created travis.yml  : Yes
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---

language: java
arch:
   - amd64
   - ppc64le   
sudo: false

