# ----------------------------------------------------------------------------
#
# Package             : attrs
# Source Repo         : https://github.com/python-attrs/attrs
# Travis Job Link     : https://travis-ci.com/github/asellappen/attrs/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 2.7
          env: TOXENV=py27
          arch : ppc64le
        - python: 3.5
          env: TOXENV=py35
          arch : ppc64le
        - python: 3.6
          env: TOXENV=py36
          arch : ppc64le
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
          arch : ppc64le
        - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true
          arch : ppc64le
before_install:
       - pip install hypothesis
       - pip install codecov
install:
  - travis_retry pip install tox

script:
  - travis_retry tox
  - coverage run conftest.py
  
# Push the results back to codecov
after_success:
  - codecov
