# ----------------------------------------------------------------------------
#
# Package             : babel-loader
# Source Repo         : https://github.com/babel/babel-loader.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/babel-loader/builds/216512194
# Created travis.yml  : Yes
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
arch: 
  - amd64
  - ppc64le
os: linux
language: node_js
node_js:
  - 'node'
  - 'lts/*'
