# ----------------------------------------------------------------------------
#
# Package             : cli
# Source Repo         : https://github.com/tektoncd/cli.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/cli/builds/217320258
# Created travis.yml  : Yes
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
os: linux
language: go
go:
  - 1.15
  - tip
