# ----------------------------------------------------------------------------
#
# Package             : datashape
# Source Repo         : https://github.com/blaze/datashape
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/datashape
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
  # Power job
    - python: 3.4.8 # Use specific minor version same as amd64. Else it fails
      arch: ppc64le
    - python: 2.7
      arch: ppc64le
    - python: 3.5
      arch: ppc64le
    - python: 3.6
      arch: ppc64le

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest==3.8.2 #Use specific version below 4.0 since a function used is later depcreated.
  - pip install mock

# command to run tests, e.g. python setup.py test
script:
  - py.test -v -x --doctest-modules --pyargs datashape -rsX --tb=short

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"
