# ----------------------------------------------------------------------------
#
# Package             : default 
# Source Repo         : https://github.com/safareli/default.git
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/default/builds/211385650
# Created travis.yml  : No
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js

node_js:
  - 14
  - 15
  
arch:
  - amd64
  - ppc64le

before_script:
  - npm install -g gulp
