# ----------------------------------------------------------------------------
#
# Package             : demjson
# Source Repo         : https://github.com/dmeranda/demjson
# Travis Job Link     : https://travis-ci.com/github/nageshlop/demjson/builds/217498736
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
language: python
dist: xenial
arch:
  - amd64
  - ppc64le
python:
  - 2.7
script:
  - make all #This will perform "build test install" as updated in the Makefile
