# ----------------------------------------------------------------------------
#
# Package             : Derby
# Source Repo         : https://github.com/apache/derby
# Travis Job Link     : https://travis-ci.com/github/rajesh-ibm-power/derby
# Created travis.yml  : Yes
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---

language: java
jdk:
  - openjdk11
  
dist: xenial

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
     - ant 1.10.7
     - maven
script:
    - cd maven2
    - mvn test
