# ----------------------------------------------------------------------------
#
# Package             : express-history-api-fallback 
# Source Repo         : https://github.com/sebdeckers/express-history-api-fallback.git
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/express-history-api-fallback/builds/211396054
# Created travis.yml  : No
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js
node_js:
  - 15
  - 14
  - 13
  - iojs
cache:
  directories:
    - node_modules
after_success:
  - npm run codecov
arch:
  - amd64
  - ppc64le
