# ----------------------------------------------------------------------------
#
# Package             : extend-shallow
# Source Repo         : https://github.com/jonschlinkert/extend-shallow.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/extend-shallow/builds/216527894
# Created travis.yml  : No
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
sudo: false
os:
  - linux
  - osx
language: node_js
#Added node_js 10 and 11
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
jobs:
  exclude:
    - node_js: '0.12'
      arch: ppc64le
    - node_js: '0.10'
      arch: ppc64le
