# ----------------------------------------------------------------------------
#
# Package             : frr
# Source Repo         : https://github.com/FRRouting/frr
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/frr/builds/216527294
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: c

dist: bionic

arch:
  - amd64
  - ppc64le

addons:
  apt:
    update: true
    packages: 
      - libtool 
      - libreadline-dev 
      - texinfo 
      - pkg-config 
      - libpam0g-dev 
      - libjson-c-dev 
      - bison 
      - flex 
      - python3-pytest 
      - libc-ares-dev 
      - python3-dev 
      - libsystemd-dev 
      - python-ipaddress 
      - python3-sphinx 
      - install-info 
      - build-essential 
      - libsystemd-dev 
      - libsnmp-dev 
      - perl 
      - libcap-dev

before_script:
      - git clone https://github.com/CESNET/libyang.git
      - cd libyang
      - mkdir build; cd build
      - cmake -DENABLE_LYD_PRIV=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -D CMAKE_BUILD_TYPE:String="Release" ..
      - make
      - sudo make install
      - cd ../..
      - sudo groupadd -r -g 92 frr
      - sudo groupadd -r -g 85 frrvty
      - sudo adduser --system --ingroup frr --home /var/run/frr/ --gecos "FRR suite" --shell /sbin/nologin frr
      - sudo usermod -a -G frrvty frr
      - pip install -U pytest  # To fix the error in travis wrt attrs
      
script: 
      - ./bootstrap.sh
      - ./configure \
        --prefix=/usr \
        --includedir=\${prefix}/include \
        --enable-exampledir=\${prefix}/share/doc/frr/examples \
        --bindir=\${prefix}/bin \
        --sbindir=\${prefix}/lib/frr \
        --libdir=\${prefix}/lib/frr \
        --libexecdir=\${prefix}/lib/frr \
        --localstatedir=/var/run/frr \
        --sysconfdir=/etc/frr \
        --with-moduledir=\${prefix}/lib/frr/modules \
        --with-libyang-pluginsdir=\${prefix}/lib/frr/libyang_plugins \
        --enable-configfile-mask=0640 \
        --enable-logfile-mask=0640 \
        --enable-snmp=agentx \
        --enable-multipath=64 \
        --enable-user=frr \
        --enable-group=frr \
        --enable-vty-group=frrvty \
        --with-pkg-git-version \
        --with-pkg-extra-version=-MyOwnFRRVersion \
        --enable-systemd=yes
      - make
      - make check
