# ----------------------------------------------------------------------------
#
# Package             : is-absolute
# Source Repo         : https://github.com/jonschlinkert/is-absolute.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/is-absolute/builds/216509177
# Created travis.yml  : No
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
sudo: false
os:
  - linux
  - osx
language: node_js
#updated with supported versions only
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
jobs:
  exclude:
     - node_js: '0.12'
       arch: ppc64le
     - node_js: '0.10'
       arch: ppc64le
