# ----------------------------------------------------------------------------
#
# Package             : JavaHamcrest
# Source Repo         : https://github.com/hamcrest/JavaHamcrest
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/JavaHamcrest/jobs/469093834
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java

os: linux

arch: 
  - amd64
  - ppc64le
  
# Need to select an older Ubuntu distribution that supports JDK7
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk11
  - openjdk14
  
# Exclude the unsupported jdk on ppc64le travis.
jobs:
  exclude:
     - arch: ppc64le
       jdk: openjdk7
     - arch: ppc64le
       jdk: oraclejdk8
     - arch: ppc64le
       jdk: openjdk8
     - arch: ppc64le
       jdk: oraclejdk9
     - arch: ppc64le
       jdk: openjdk14


# Workaround to using openjdk7 with Gradle due to security issue:
# https://github.com/gradle/gradle/issues/2421

before_install:
- |
  if [ "$TRAVIS_CPU_ARCH" != ppc64le ]; then  # ppc64le doesn't have openjdk7. This is not needed
   BCPROV_FILENAME=bcprov-ext-jdk15on-158.jar;
   wget "https://bouncycastle.org/download/${BCPROV_FILENAME}";
   sudo mv $BCPROV_FILENAME /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext;
   sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security;
   echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security;
  fi
  
script:
  - ./gradlew clean build javadoc
