# ----------------------------------------------------------------------------
#
# Package             : jcabi-manifests
# Source Repo         : https://github.com/jcabi/jcabi-manifests
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/jcabi-manifests/builds/215523681
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java
arch:
   - amd64
   - ppc64le
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd --source=$(pwd) --file=/dev/null
  # est not supported on ppc64le. Excluding it.
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then est --dir=est --file=/dev/null; fi
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then gem install est -v 0.3.4; fi
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
