# ----------------------------------------------------------------------------
#
# Package             : loopback-component-storage
# Source Repo         : https://github.com/strongloop/loopback-component-storage.git
# Travis Job Link     : https://travis-ci.com/github/genisysram/loopback-component-storage/builds/211133660
# Created travis.yml  : No
# Maintainer          : <ramakrishna.s@genisys-group.com>,<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
    - amd64
    - ppc64le
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
