# ----------------------------------------------------------------------------
#
# Package             : loopback-sdk-angular-cli
# Source Repo         : https://github.com/strongloop/loopback-sdk-angular-cli.git
# Travis Job Link     : https://travis-ci.com/github/genisysram/loopback-sdk-angular-cli/jobs/469731227
# Created travis.yml  : No
# Maintainer          : <ramakrishna.s@genisys-group.com>,<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------


sudo: false
arch:
    - amd64
    - ppc64le
language: node_js
node_js:
  - "8"
  - "10"

