# ----------------------------------------------------------------------------
#
# Package             : mothur
# Source Repo         : https://github.com/mothur/mothur
# Travis Job Link     : https://travis-ci.com/github/ujjwalsh/mothur/builds/213262386
# Created travis.yml  : No
# Maintainer          : Ujjwal Sharma <ujjwal.cpp@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------



language: C++
os:
 - osx
 - linux

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
      - libreadline6
      - libreadline6-dev
      - libboost-all-dev

before install:
  - if [[ "TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "TRAVIS_OS_NAME" == "osx" ]]; then brew install readline boost; fi

script: make install

