# ----------------------------------------------------------------------------
# #
# # Package             : node-assert-plus
# # Source Repo         : https://github.com/mcavage/node-assert-plus.git
# # Travis Job Link     : https://travis-ci.com/github/sanjaymsh/node-assert-plus
# # Created travis.yml  : Yes
# # Maintainer          : Sanjay Mishra <snjkmr32@gmail.com>
# #
# # Script License      : Apache License, Version 2 or later
# #
# # -------------------------------------------------------------------------- 

os: linux
arch:
  - amd64
  - ppc64le
script:
   - make
   - make test
