# ----------------------------------------------------------------------------
#
# Package             : noggit
# Source Repo         : https://github.com/yonik/noggit
# Travis Job Link     : https://travis-ci.com/github/nageshlop/noggit/builds/216090388
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
dist: xenial
arch:
  - amd64
  - ppc64le
language: java
script:
  - mvn clean:clean 
  - mvn install -Dmaven.javadoc.skip=true -B -V
