# ----------------------------------------------------------------------------
# Package             : q
# Source Repo         : https://github.com/kriskowal/q.git
# Travis Job Link     : https://travis-ci.com/github/genisysram/q/jobs/469733653
# Created travis.yml  : No
# Maintainer          : <ramakrishna.s@genisys-group.com>,<sethp@us.ibm.com>
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
    - amd64
    - ppc64le
language: node_js
node_js:
  - "15"
script:
  npm test
