# ----------------------------------------------------------------------------
#
# Package             : strong-service-systemd
# Source Repo         : https://github.com/strongloop/strong-service-systemd
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/strong-service-systemd/builds/212441397
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js

node_js:
   - 10
   
arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget 
