# ----------------------------------------------------------------------------
#
# Package             : strong-url-defaults
# Source Repo         : https://github.com/strongloop/strong-url-defaults
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/strong-url-defaults/jobs/479596398
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js

node_js:
   - 10
   - 12
   - lts/*
   - node
   
arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget 
