# ----------------------------------------------------------------------------
#
# Package             : tzlocal
# Source Repo         : https://github.com/regebro/tzlocal
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/tzlocal/builds/215909934
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

dist: bionic

python: 3.9
   
arch:
   - amd64
   - ppc64le   

install:
   - pip install .[test]
   - pip install tzdata
   - python setup.py install

script: 
   - pytest
