# ----------------------------------------------------------------------------
#
# Package             : watchdog
# Source Repo         : https://github.com/gorakhargosh/watchdog
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/watchdog/builds/215892669
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

# Beta opt-in
# https://docs.travis-ci.com/user/build-config-validation#beta-opt-in
version: ~> 1.0

language: python
dist: xenial
os: linux

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  fast_finish: true
  include:
    - name: Python 3.6 on GNU/Linux
      os: linux
      python: "3.6"
      env:
        - TOXENV=py36
        # To help catch regression seen in #615
        - LC_ALL=C
    - name: Python 3.7 on GNU/Linux
      os: linux
      python: "3.7"
      env: TOXENV=py37
    - name: Python 3.8 on GNU/Linux
      os: linux
      python: "3.8"
      env: TOXENV=py38
    - name: Python 3.9 on GNU/Linux
      os: linux
      python: "3.9"
      env: TOXENV=py39
    - name: Python 3.10 on GNU/Linux
      os: linux
      python: nightly
      env: TOXENV=py310

    - name: PyPy 3.6 on GNU/Linux
      os: linux
      python: pypy3
      env: TOXENV=pypy3

    - name: Python 3.6 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.6.12
        - pyenv global 3.6.12
      env:
        - TOXENV=py36
        - PYENV_ROOT="$HOME/.pyenv/versions/3.6.12"
        - PATH="$PYENV_ROOT/bin:$PATH"
    - name: Python 3.7 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.7.9
        - pyenv global system 3.7.9
      env:
        - TOXENV=py37
        - PYENV_ROOT="$HOME/.pyenv/versions/3.7.9"
        - PATH="$PYENV_ROOT/bin:$PATH"
    - name: Python 3.8 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.8.6
        - pyenv global system 3.8.6
      env:
        - TOXENV=py38
        - PYENV_ROOT="$HOME/.pyenv/versions/3.8.6"
        - PATH="$PYENV_ROOT/bin:$PATH"
    - name: Python 3.9 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.9.0
        - pyenv global system 3.9.0
      env:
        - TOXENV=py39
        - PYENV_ROOT="$HOME/.pyenv/versions/3.9.0"
        - PATH="$PYENV_ROOT/bin:$PATH"
    - name: Python 3.10 on macOS
      os: osx
      language: shell
      install:
        - unset PYENV_ROOT
        - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        - eval "$(pyenv init -)"
        - pyenv install --skip-existing 3.10-dev
        - pyenv global system 3.10-dev
      env:
        - TOXENV=py310
        - PYENV_ROOT="$HOME/.pyenv/versions/3.10-dev"
        - PATH="$PYENV_ROOT/bin:$PATH"

    - name: Python 3.6 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=3.6.8
      env:
        - TOXENV=py36
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
    - name: Python 3.7 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=3.7.9
      env:
        - TOXENV=py37
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - name: Python 3.8 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=3.8.6
      env:
        - TOXENV=py38
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - name: Python 3.9 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=3.9.0
      env:
        - TOXENV=py39
        - export PATH="/c/Python39:/c/Python39/Scripts:$PATH"
    - name: Python 3.10 on Windows
      os: windows
      language: shell
      before_install:
        - choco install python3 --pre
      env:
        - TOXENV=py310
        - export PATH="/c/Python310:/c/Python310/Scripts:$PATH"
        
# Power jobs
    - name: Python 3.7 on ppc64le
      os: linux
      arch: ppc64le
      python: "3.7"
      env: 
        - TOXENV=py37
        - PYTHONIOENCODING=UTF-8 # To fix ascii issue 
    - name: Python 3.8 on ppc64le
      os: linux
      arch: ppc64le
      python: "3.8"
      env: 
        - TOXENV=py38
        - PYTHONIOENCODING=UTF-8 # To fix ascii issue 
    - name: Python 3.9 on ppc64le
      os: linux
      arch: ppc64le
      python: "3.9"
      env: 
        - TOXENV=py39
        - PYTHONIOENCODING=UTF-8 # To fix ascii issue 

before_script:
  - python -V
  - python -m pip install -U pip tox
  - python -m tox --notest  # Note: keep it!

script:
  - python -m tox

notifications:
  email: false
