# ----------------------------------------------------------------------------
#
# Package             : XlsxWriter
# Source Repo         : https://github.com/jmcnamara/XlsxWriter.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/XlsxWriter/builds/212183444
# Created travis.yml  : No
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le

language: python

dist: xenial
os: linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "3.10-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
jobs:
  exclude:
    - python: "pypy"
      arch: ppc64le
    - python: "pypy3"
      arch: ppc64le

install:
- pip install pytest
- pip install pycodestyle

script:
- py.test
- make test_codestyle
- make testwarnings
