# ----------------------------------------------------------------------------
#
# Package             : zookeeper
# Source Repo         : https://github.com/apache/zookeeper
# Travis Job Link     : https://travis-ci.com/github/dthadi3/zookeeper/builds/211741363
# Created travis.yml  : No
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      arch: ppc64le
      jdk: openjdk8
    - os: linux
      arch: ppc64le
      jdk: openjdk11
    - os: linux
      arch: arm64
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get install maven;
    fi

script: mvn clean apache-rat:check verify -DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4
